### ISSUE TITLE
Items & Holdings Supported?

### ISSUE THREAD

**Issue by gpeterso** [ExLibrisGroup/cloudapp-sdk#18]
Are `ITEM` and `HOLDING` requests supported? Whenever I attempt to retrive items or holdings via the `CloudAppRestService`, I get a 401 (unauthorized) error. 

Additional details: 
- Bib requests (e.g. `call('/bib/...')`) work fine, but any holding or item requests result in a 401 response. e.g.: 
  - `call('/bib/.../holdings')`
  - `call('bib/.../holdings/.../items)` 
- I've confirmed that the currently-authenticated user can view/edit/delete item records in the UI without any problems, so the 401 error seems odd. 
- For the sake of completeness, I tried adding *all* Inventory and Catalog roles to the user account (with institutional scope) and then re-authenticated (after deleting cookies, session storage and local storage), but simple GET requests for holdings and items continued to return 401 codes.  
- I randomly tried a few endpoints under `/conf` and `/user`. Those worked as expected. 

I suspect I'm missing something, but I'm stumped...

Jeff

**Comment by jweisman** [comment]
Hi Jeff. Thanks for raising this issue. I think the permissions for this API from Cloud Apps is not 100% right. Currently the following roles have the necessary privilege:

* Circulation Desk Manager
* Circulation Desk Operator
* Circulation Desk Operator Limited
* Requests Operator
* Work Order Operator

We plan to add the following roles as well (from the December release):
* Fulfillment Services
* Fulfillment Services Manager
* License Manager
* Physical Inventory Operator
* Purchase Manager
* Purchase Operator
* Receiving Operator
* Receiving Manager

But hopefully this information will allow you to designate the proper roles so you can make progress.

**Comment by gpeterso** [comment]
Ah, this must have something to do with the "scan in" operation. 

Adding the request operator role gave me what I needed. I doubt that we'll be able rely on this for production, but it's sufficient for an initial prototype. Glad to hear about the December plans...

Thanks for the info, Josh!
