### ISSUE TITLE
New event service back/home messages

### ISSUE THREAD

**Issue by gpeterso** [ExLibrisGroup/cloudapp-sdk#23]
Hello, 

Does Alma already support these messages, or is this part of a future release?

https://github.com/ExLibrisGroup/cloudapp-sdk/blob/6ed5c086672118b91cb327d4f91939423dfde3e5/angular-lib/src/lib/messages/messages.ts#L21-L22

**Comment by jweisman** [comment]
Hi @gpeterso . This will be supported from the Jan 2021 Alma release. We'll update the [documentation](https://developers.exlibrisgroup.com/cloudapps/docs/api/events-service/) along with the sandbox release on Dec 20.
