### ISSUE TITLE
CLI allows access to parent DOM

### ISSUE THREAD

**Issue by jweisman** [ExLibrisGroup/cloudapp-sdk#28]
The CLI allows access to the parent DOM which production does not. That's because the sandbox iframe includes `allow-same-origin` and the CLI runs the `ng` dev environment and the Alma proxy on the same host/port. The `allow-same-origin` policy is set to allow limiting `postMessage` by origin. (See [here](https://stackoverflow.com/questions/50480198/how-to-correctly-postmessage-into-an-iframe-that-has-sandbox-attribute-enabled/50480492) and [here](https://javascript.info/cross-window-communication#the-sandbox-iframe-attribute)). The problem is that developers may think they can access the Alma DOM while in production it won't work.

This issue is to decide whether to remove the `allow-same-origin` policy in order to provide a more consistent development environment and provide guidance about the null origin.

**Comment by jweisman** [comment]
Added a [popup section](https://developers.exlibrisgroup.com/cloudapps/tutorials/outside/#postmessage) to the external tutorial with a "note about origins." Opened Jira to remove `allow-same-origin`.

**Comment by ori229** [comment]
allow-same-origin will not appear starting Alma's July 2021 release.
