### ISSUE TITLE
Initial loading indicator

### ISSUE THREAD

**Issue by SydneyUni-Jim** [ExLibrisGroup/cloudapp-sdk#34]
While the initial assets for an app are downloading, there is nothing on the Alma screen except the app's title. An app with a sizeable main.js can take seconds to come to life.

Could we please get an initial loading indicator if an app does not come to life "quickly"?

**Comment by jweisman** [comment]
Hi @SydneyUni-Jim . This was done in the [latest release](https://github.com/ExLibrisGroup/cloudapp-sdk/releases/tag/v1.0.1). Will take affect for each app on the next build without the need to bump the app to the latest SDK version.

Let us know how this works for you.

**Comment by SydneyUni-Jim** [comment]
Hi @jweisman. To simulate a slow network or large payload, I cleared my cache and throttled my network to «Good 2G». Acknowledging this to be an extreme test, there was a significant period before the loading indicator appeared. When the indicator did appear, it was very brief before the app came to life.

I've shared a record of my screen at https://www.screencast.com/t/HKHVIn5E

**Comment by jweisman** [comment]
Hi @SydneyUni-Jim - I would probably focus on optimizing for 3G since 2G sounds pretty extreme and unlikely for Alma users. Can you check with that throttling? For me it looks pretty good:


https://user-images.githubusercontent.com/80420/120099039-f86f2280-c141-11eb-828c-836eb389a52f.mov
