### ISSUE TITLE
"Value could not be determined statically." error in build

### ISSUE THREAD

**Issue by jweisman** [ExLibrisGroup/cloudapp-sdk#43]
Cannot use `getTranslateModule` function in `ngModel` imports:

```
Error: src/app/app.module.ts:41:12 - error NG1010: Value at position 8 in the NgModule.imports of AppModule is not a reference
  Value could not be determined statically.

 41   imports: [
               ~
 42     MaterialModule,
    ~~~~~~~~~~~~~~~~~~~
... 
 50     getTranslateModule(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~
 51   ],
    ~~~
```

**Comment by jweisman** [comment]
Replicated by @ori229

**Comment by jweisman** [comment]
Resolved in npm install -g @exlibris/exl-cloudapp-cli@1.2.4

**Comment by exlbashirn** [comment]
@jweisman I'm not sure if you reopened this for me to comment on or because it's still an open issue, but this should be perfectly fine. No issues that I could see when testing.

**Comment by jweisman** [comment]
Thanks @exlbashirn !
