### ISSUE TITLE
Cannot login via proxy

### ISSUE THREAD

**Issue by jweisman** [ExLibrisGroup/cloudapp-sdk#48]
From @d22 on #40:

> But I'm still not able to work, since the login does not work. After logging in, I always get redirected to back to the login page. The behaviour is the same on Windows and OSX, and also the same with Node 16.x.x.
So currently we are completely blocked from working on CloudApps, any hint or help on how to fix this is appreciated.

**Comment by jweisman** [comment]
Hi @d22 - I think we've found the root cause in the environment configuration. Here is a workaround- please create a file called *proxy.conf.js* in the *cloudapp/src/* directory with the following contents:

```
const {target} = require("../config.json");

const PROXY_CONFIG = {
  "/": {
      target,
      secure: false,
      onProxyRes: (proxyRes, req, res) => {
          let cookies =  proxyRes.headers['set-cookie'];
          cookies && cookies.forEach((val, i, arr) => {
              const parts = val.split(";").map(p=>p.trim());
              arr[i] = parts.filter(p=>p.match(/^(?!SameSite|Secure)/i)).join('; ')
              /* Handle sticky cookie for load balancer */
              .replace(/__Secure-/g, "KUKUBALALA");
          });
          proxyRes.headers['set-cookie'] = cookies;
      },
      onProxyReq: (proxyReq, req, res) => {
          let cookies = req.headers['cookie'];
          /* Handle sticky cookie for load balancer */
          cookies && proxyReq.setHeader('Cookie', cookies.replace(/KUKUBALALA/g, "__Secure-"));
      }
  }
}

module.exports = PROXY_CONFIG;
```

Then do `eca start`. Let us know how that works and we'll follow up with a report on getting the root cause fixed.

**Comment by d22** [comment]
Hi @jweisman 
Thanks a lot for this workaround, it works! 
Jonas

**Comment by jweisman** [comment]
Great @d22 - thanks for the confirmation. We’ll include the change in the next version of the CLI. You can continue to use the workaround in the meantime.
